---
title: "Soil sample plan"
author: "Stanley Mastrantonis"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(leaflet)
library(mapview)
library(mapedit)
library(leafpm)
library(leafem)
library(shiny)
library(tidyverse)
library(raster)
library(terra)
#webshot::install_phantomjs()

```

```{r data read in, include = TRUE}
cpes = st_read('C:/Users/00097030/LocalData/Spatial Data/CPES/shp/CPES_ag.shp')%>%
       st_transform(4326)%>%
       st_make_valid()
       #st_cast('POLYGON')
       #st_union()

#cpes_wgs  = st_transform(cpes, 4326)

radmap = rast('C:/Users/00097030/LocalData/Spatial Data/RADmap/Tiff/clipped/RGB_Stack.tif')

```


```{r leaflet draw, include = FALSE}
i <<- 1
i_edit <<- 1
feat_list  <<- list()
edit_list <<- list()

ui = fluidPage(
  tabsetPanel(
    tabPanel("Map",
             leafletOutput("mymap", width="100%",height="600px"),
             textInput("label", "Label", "Smith_Pad_1_Soil"),
             downloadButton( outputId = "dl"),
             actionButton(inputId = "quit", label = "Quit")
    ),
    tabPanel("Debug",
             verbatimTextOutput("debug_out")
    )
  )
  
)


server = function(input, output, session){
  output$debug_out = renderPrint(reactiveValuesToList(input))
  mymap = reactiveValues(dat = 0)
  
  output$mymap = renderLeaflet({
  mymap$dat = leaflet() %>%
      addProviderTiles("Esri.WorldImagery") %>%
      addScaleBar(position = "bottomleft") %>%
      addMiniMap(tiles = providers$Esri.NatGeoWorldMap) %>%
      addPolygons(data = cpes,  
                   opacity = 0.5,
                   color = 'red',
                   weight = 2,
                   fill = FALSE,
                   fillColor = 'red',
                   fillOpacity = 0.1,
                   group = "CPES") %>%
      setView(lng = 116, lat = -30.0, zoom = 5) %>%
      groupOptions("CPES", zoomLevels = 7:500) %>%
      addMouseCoordinates() %>%
      addLayersControl(overlayGroups = c("CPES"))%>%
      addPmToolbar(targetGroup = 'draw',
        toolbarOptions = pmToolbarOptions(drawMarker = FALSE, 
                                          drawPolyline = FALSE,
                                          cutPolygon = TRUE,
                                          position = "topright"),
        drawOptions = pmDrawOptions(snappable = FALSE, allowSelfIntersection = FALSE),
        editOptions = pmEditOptions(preventMarkerRemoval = TRUE, draggable = TRUE),
        cutOptions = pmCutOptions(snappable = FALSE, allowSelfIntersection = FALSE)
      )
  })
  
  
  observeEvent(input$mymap_draw_new_feature,{
    #print(input)
    feature <<- input$mymap_draw_new_feature
    feat_list[[i]] <<- geojsonsf::geojson_sf(jsonify::to_json(feature, unbox = T))
    i <<- i+1
  })
  
  observeEvent(input$mymap_draw_edited_features, {
    cutfeature <<- input$mymap_draw_edited_features
    edit_list[[i]] <<- geojsonsf::geojson_sf(jsonify::to_json(cutfeature, unbox = T))
    i_edit <<- i_edit+1
    #print(cutfeature)
    
  })
  
  
    observe({
      if (input$quit == 1) stopApp()
     })


  
  output$dl = downloadHandler(
        filename = "map.png",
        content = function(file) {
          mapshot(mymap$dat, file = file)
        }
      )
  

  
}

shinyApp(ui = ui, server = server)
```

```{r bind, include = FALSE}

result = do.call(rbind, lapply(feat_list, st_sf))
pol_vec = vect(result)
rad_crop = brick(terra::crop(radmap, pol_vec, mask=TRUE, snap = 'out'))

map_aoi_create = leaflet() %>% 
                 addTiles() %>% 
                 addRasterRGB(rad_crop,3,2,1, group = "RADmap", na.color = NA)%>%
                 addPolygons(data = result) %>%
                 addProviderTiles("Esri.WorldImagery") %>%
                 addLayersControl(overlayGroups = c("RADmap"))%>%
                 #setView(lng = -166, lat = 58.0, zoom = 5) %>%
                 #addMouseCoordinates() %>%
                 addScaleBar()  
  
map_aoi_create



```

